### PR TITLE
pass ice servers to file transfer session

### PR DESCRIPTION
**Pull request by sualko**
Any drawbacks on this?

### CODE REVIEW

**Comment by xdumaine** [comment]
Makes sense to me. Looks like CI is broken due to a chrome dep.

**Comment by fippo** [comment]
the .travis.yml needs a major update...

**Comment by fippo** [comment]
can you rebase and force-push? i'd like to test that CI is now green

**Comment by sualko** [comment]
Everything green :+1:

**Comment by fippo** [comment]
published as 3.0.3, thanks!

**Pull request merged**
